### ISSUE TITLE
Please Share Dockerfile of "ccr.ccs.tencentyun.com/autodl-private-cloud/miniconda:cuda11.8-cudnn8-devel-ubuntu22.04-py310"

### ISSUE THREAD

**Issue by ammadkhalid** [mayooot/grok-docker#1]
Hello,

I am currently working with the image **ccr.ccs.tencentyun.com/autodl-private-cloud/miniconda:cuda11.8-cudnn8-devel-ubuntu22.04-py310** and would greatly appreciate it if you could share the **Dockerfile** used to build this image.

Additionally, if you could provide guidance on how to locate **Dockerfiles** for specific images in your repository, it would be extremely helpful for future reference.

I am also interested in Alpine version Of that image too! If That is not built, already then I will build it, myself!

Thank you! 谢谢！

**Comment by mayooot** [comment]
> Hello,
> 
> I am currently working with the image **ccr.ccs.tencentyun.com/autodl-private-cloud/miniconda:cuda11.8-cudnn8-devel-ubuntu22.04-py310** and would greatly appreciate it if you could share the **Dockerfile** used to build this image.
> 
> Additionally, if you could provide guidance on how to locate **Dockerfiles** for specific images in your repository, it would be extremely helpful for future reference.
> 
> I am also interested in Alpine version Of that image too! If That is not built, already then I will build it, myself!
> 
> Thank you! 谢谢！

Sorry, I'm not an AutoDL employee so I don't know what the Dockerfile about build image.

Actually you can just use [cuda](https://hub.docker.com/r/nvidia/cuda/) as the base image, then install python, pip .... , and just commit it to a image.

No need to get too hung up on the Dockerfile. 😊

**Comment by mayooot** [comment]
> Hello,
> 
> I am currently working with the image **ccr.ccs.tencentyun.com/autodl-private-cloud/miniconda:cuda11.8-cudnn8-devel-ubuntu22.04-py310** and would greatly appreciate it if you could share the **Dockerfile** used to build this image.
> 
> Additionally, if you could provide guidance on how to locate **Dockerfiles** for specific images in your repository, it would be extremely helpful for future reference.
> 
> I am also interested in Alpine version Of that image too! If That is not built, already then I will build it, myself!
> 
> Thank you! 谢谢！

@kmkmjhyiiiu This is a list of docker image you can refer to: https://private.autodl.com/docs/image/
